YEAR = 2026
AUTHOR = "Dhiraj Kumar Singh"
VERSION = "4.1.1"
DESKTOP_ID = "com.dhirajkumarsingh.XenpaiKartDownloader"
DESKTOP_OBJECT_PATH = "/" + DESKTOP_ID.replace(".", "/")
LATEST_EXTENSION_VERSION = "2.1.0"
AUTHOR_URL = ""
FEEDBACK_URL = "https://github.com/XiaoYouChR/Ghost-Downloader-3/issues"
FIREFOX_ADDONS_URL = "https://addons.mozilla.org/zh-CN/firefox/addon/ghost-downloader/"
EDGE_ADDONS_URL = "https://microsoftedge.microsoft.com/addons/detail/ghost-downloader-browser/odaohmfjjbompdkmfbambadnagplcmce"
CHROME_WEBSTORE_URL = "https://chromewebstore.google.com/detail/ghost-downloader-for-brow/lagbjgkmaafnlinaeonbhjchnjinjpeh"
